---
name: im-scikit-learn
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - rdkit=2024.03.2
  - scikit-learn=1.4.1.post1
  - pandas=2.1
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - pytdc=0.3.8
  - skl2onnx=1.15.0
  - onnxruntime=1.15.0
  - pip:
    - im-standardize-molecule==0.1.0
    - im-data-manager-job-utilities==1.1.1
    - jaqpotpy
    - scikit-mol
